version: '3'

services:
  app:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    container_name: micro-catalog-app
    ports:
      - 3001:3000
    environment:
      - HOST=0.0.0.0
    volumes:
      - .:/home/node/app
    networks:
      - app-network
      - micro-rabbitmq_micro-catalog

  # config tutorial: https://www.elastic.co/guide/en/elastic-stack-get-started/current/get-started-docker.html
  # TODO: set security config https://www.elastic.co/guide/en/elasticsearch/reference/7.16/security-minimal-setup.html#_prerequisites_10
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    container_name: micro-catalog-elasticsearch
    environment:
      - discovery.type=single-node
    volumes:
      - ./.docker/elasticdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - app-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.3
    container_name: micro-catalog-kibana
    ports:
      - 5601:5601
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
  micro-rabbitmq_micro-catalog:
    external: true
